 const jobCategories = [
    [
      { name: "Business Management", count: 3 },
      { name: "Web Developer", count: 2 },
      { name: "Bank Operation", count: 1 },
      { name: "Marketing", count: 1 },
      { name: "Software & Web Development", count: 1 },
      { name: "IT & Software Development", count: 1 },
      { name: "Data Science", count: 1 },
      { name: "Cybersecurity", count: 1 },
      { name: "Cloud Computing", count: 1 },
      { name: "Artificial Intelligence", count: 1 },
      { name: "Machine Learning", count: 1 },
      { name: "DevOps Engineering", count: 1 },
      { name: "Blockchain Development", count: 1 },
      { name: "Mobile App Development", count: 1 },
      { name: "Network Engineering", count: 1 },
      { name: "UI/UX Design", count: 1 },
    ],
    [
      { name: "Creative Design", count: 3 },
      { name: "Database Administration (DBA)", count: 1 },
      { name: "Graphic Design", count: 1 },
      { name: "Business Systems Analyst", count: 1 },
      { name: "Electronics Technician", count: 1 },
      { name: "Web Content Writer", count: 1 },
      { name: "Digital Marketing", count: 1 },
      { name: "Video Editor", count: 1 },
      { name: "Motion Graphics Designer", count: 1 },
      { name: "3D Modeling Artist", count: 1 },
      { name: "Game Designer", count: 1 },
      { name: "Sound Engineer", count: 1 },
      { name: "Photography", count: 1 },
      { name: "Animation", count: 1 },
      { name: "Illustration", count: 1 },
      { name: "Brand Identity Designer", count: 1 },
      { name: "Print Designer", count: 1 },
      { name: "Art Director", count: 1 },
      { name: "Visual Effects Artist", count: 1 },
      { name: "Interior Designer", count: 1 }
    ],
    [
      { name: "Admin", count: 2 },
      { name: "Advertising", count: 1 },
      { name: "Medicine", count: 1 },
      { name: "Accounts, Finance & Financial Services", count: 1 },
      { name: "Human Resources", count: 1 },
      { name: "Legal Services", count: 1 },
      { name: "Project Management", count: 1 },
      { name: "Supply Chain Management", count: 1 },
      { name: "Customer Service", count: 1 },
      { name: "Sales & Business Development", count: 1 },
      { name: "Research & Development", count: 1 },
      { name: "Quality Assurance", count: 1 },
      { name: "Operations Management", count: 1 },
      { name: "Risk Management", count: 1 },
      { name: "Public Relations", count: 1 },
      { name: "Event Management", count: 1 },
      { name: "Real Estate", count: 1 },
      { name: "Logistics", count: 1 },
      { name: "Hospitality Management", count: 1 },
      { name: "Education & Training", count: 1 },
      { name: "Consulting", count: 1 }
    ],
  ];


  export { jobCategories };
